### ISSUE TITLE
Table API properties use fixed and render got error

### ISSUE THREAD

**Issue by Isabella-Zheng** [trendmicro-frontend/react-table#21]
I use the API properties of column with fixed and render, but it cause errors:
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

What could I do to solve it?

**Comment by tinaClin** [comment]
Hi @Isabella-Zheng,
Could you provide the sample code that how do you render columns? Thanks.

**Comment by Isabella-Zheng** [comment]
Here is simplified code:
```sh
class MyApp extends Component {
  // ... 
  
  render() {
    const renderO = {
      renderActionCell: (value, row) => {
        return (
          <i
            className="fa fa-pencil i-edit"
            onClick={this.onClick}
          />
        );
      },
      renderAddressId: (value, row) => {
        return row['addressId'];
      },
      renderCheckbox: (value, row, idx) => {
        return this.state.provider === true ? (
          <div>{idx + 1}</div>
        ) : (
          <Checkbox
            value={row['providerInfo']}
            name={row['providerInfo']}
            onChange={event => {
              // do something
            }}
          />
        );
      }
    };
  
    const columns = [
      {
        title:
          this.state.provider === true ? (
            <div> NO.</div>
          ) : (
            <Checkbox
              onChange={event => {
                // do something
              }}
            />
          ),
        render: renderO.renderCheckbox,
        headerClassName: 'table-td',
        className: 'table-td',
        width: 50
      },
      {
        title: 'Actions',
        render: renderO.renderActionCell,
        width: 110,
        headerClassName: 'table-td',
        className: 'table-td',
        fixed: true
      },
      {
        title: 'Address',
        render: renderO.renderAddressId,
        headerClassName: 'table-td',
        className: 'table-td',
        width: 1800
      }
    ];
  
  return (
    <div>
      <Table
        className="m-table"
        columns={columns}
        data={data}
        useFixedHeader={true}
        emptyText={() => {
          return 'No Data';
        }}
        maxHeight={500}
      />
    </div>
  )
  
}

export default MyApp;
```

**Comment by roth1002** [comment]
Hi @Isabella-Zheng 
 
   We have some remainded issue on fixed column and restrictions

   Ex:  the un-needed scrolling for x-axis was controlled here 

https://github.com/trendmicro-frontend/react-table/blob/0a9a9f65cfe93f1ede8ad2a85be603c3cee5cd63/src/table-fixed.styl#L37

https://github.com/trendmicro-frontend/react-table/blob/0a9a9f65cfe93f1ede8ad2a85be603c3cee5cd63/src/table-fixed.styl#L10

Hi @tinaClin 

   The try update for unmounted component heppended when fixed left table be shown or not

   may try to fixed by reference this

   https://github.com/jaredpalmer/formik/commit/915bae5af4c4eff7bcc7cb5474bf02cef2a9c9fb

   and use setState after the didMount boolean argument for true.

   I would find you and @cheton  to discuss this issue :)

**Comment by tinaClin** [comment]
Hi @Isabella-Zheng,
Please use the table of v2.0.1 to implement fixed column, you can refer [the example code](https://github.com/trendmicro-frontend/react-table/blob/master/styleguide/examples/FixedColumns.jsx), that will help to solve the render issue.
